version: '2.2'
services:
    service-discovery:
        container_name: service-discovery
        build:
            context: ./service-discovery
        image: service-discovery:latest
        ports:
            - 8761:8761
